name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Ensure homepage is set in package.json
      - name: Ensure homepage in package.json
        run: |
          URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "Setting homepage=$URL"
          jq ".homepage = \"$URL\"" package.json > package.tmp.json && mv package.tmp.json package.json

      # 4. Ensure react-scripts is installed
      - name: Ensure react-scripts dependency
        run: |
          if ! npm list react-scripts >/dev/null 2>&1; then
            echo "react-scripts missing, installing..."
            npm install react-scripts --save
          fi

      # 5. Install dependencies
      - name: Install dependencies
        run: npm install

      # 6. Build React app (logs redirected to build.log)
      - name: Build React app
        run: |
          npm run build --if-present --verbose 2>&1 | tee build.log

      # 7. Upload build logs (always runs, even if build fails)
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log

      # 8. Deploy to GitHub Pages (only if build succeeds)
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
