name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Ensure homepage in package.json
        run: |
          URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "Setting homepage=$URL"
          jq ".homepage = \"$URL\"" package.json > package.tmp.json && mv package.tmp.json package.json

      - name: Ensure react-scripts dependency
        run: |
          if ! npm list react-scripts >/dev/null 2>&1; then
            echo "react-scripts missing, installing..."
            npm install react-scripts --save
          fi

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: |
          npm run build --if-present --verbose 2>&1 | tee build.log

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
