name: Build and Deploy Vite React App

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - run: npm install

      # 4. Build project and save log
      - name: Build
        run: |
          npm run build 2>&1 | tee build.log

      # 5. Upload build log (always runs) using v4
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      # 6. Upload dist/ as GitHub Pages artifact
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist  # Vite output folder

      # 7. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
